export enum LayoutsEnum {
    ACCOUNT = 'ACCOUNT',
    NEWS = 'NEWS',
    TRACKING = 'TRACKING',
    CALENDAR = 'CALENDAR',
    CHALLENGES = 'CHALLENGES',
    MEALS = 'MEALS',
    LIBRARY = 'LIBRARY',
    MESSAGES ='MESSAGES',
    CLASSES = 'CLASSES',
    NOTIFICATIONS = 'NOTIFICATIONS',
    ALBUMS = 'ALBUMS',

    MESSAGES_INTO ='MESSAGES_INTO',
    BODY ='BODY',
}
